name: forms-flow-shared using matrix

on:
  workflow_dispatch:
    inputs:
      START_BUILD:
        required: true
        type: boolean
        description: This value is ignored, just to trigger dispatch.
  push:
    branches:
      - dev
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'forms-flow-ai/**'
      - '.github/workflows/**'

defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    if: github.repository == 'bcgov/nr-epd-digital-services'
    strategy:
      matrix:
        app:
          [
            'forms-flow-bpm',
            'forms-flow-nav',
            'forms-flow-theme',
            'forms-flow-web-ee',
            'forms-flow-web-root-config',
            'forms-flow-web',
          ]
        directory:
          [
            './forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-theme',
            './forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm',
            './forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-nav',
            './forms-flow-ai/forms-flow-ai-ee/forms-flow-web',
            './forms-flow-ai/forms-flow-ai-ee/forms-flow-web-root-config',
            './forms-flow-ai/forms-flow-web',
          ]

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    env:
      APP_NAME: ${{ matrix.app }}

    steps:
      - uses: actions/checkout@v2
      - name: Set ENV variables
        id: set-variable
        run: |
          if [ '${{ github.ref_name }}' == 'dev' ]; then
            echo "For ${{ github.ref_name }} branch"
            echo "TOOLS_NAME=${{secrets.OC_NAMESPACE_NAMEPLATE}}" >> $GITHUB_ENV
            echo "TAG_NAME="dev"" >> $GITHUB_ENV
            echo "BRANCH_NAME="dev"" >> $GITHUB_ENV
            echo "ENV_NAME="dev"" >> $GITHUB_ENV
          elif [ '${{ github.ref_name }}' == 'main' ]; then
            echo "For ${{ github.ref_name }} branch"
            echo "TOOLS_NAME=${{secrets.OC_NAMESPACE_NAMEPLATE}}" >> $GITHUB_ENV
            echo "TAG_NAME="test"" >> $GITHUB_ENV
            echo "BRANCH_NAME="main"" >> $GITHUB_ENV
            echo "ENV_NAME="test"" >> $GITHUB_ENV
          else
            echo "For ${{ github.ref_name }} branch, defaulting to dev values"
            echo "TOOLS_NAME=${{secrets.OC_NAMESPACE_NAMEPLATE}}" >> $GITHUB_ENV
            echo "TAG_NAME="dev"" >> $GITHUB_ENV
            echo "BRANCH_NAME="dev"" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OC_SERVER}} --token=${{secrets.OC_TOKEN}}

      - name: Tools project
        shell: bash
        run: |
          oc project ${{ secrets.OC_NAMESPACE_NAMEPLATE }}-tools

      # Build from either dev or main branch as appropriate
      - name: Build from ${{ env.BRANCH_NAME }} branch
        if: env.APP_NAME != 'forms-flow-web-root-config' # This step will be skipped for 'forms-flow-web-root-config'
        shell: bash
        run: |
          oc patch bc/${{ env.APP_NAME }}-build -p '{"spec":{"source":{"git":{"ref":"${{ env.BRANCH_NAME }}"}}}}'

      - name: Start Build Openshift
        shell: bash
        run: |
          oc start-build ${{ env.APP_NAME }}-build --wait

      - name: Tag+Deploy for ${{ env.TAG_NAME }}
        if: env.APP_NAME != 'forms-flow-web-root-config' # This step will be skipped for 'forms-flow-web-root-config'
        shell: bash
        run: |
          oc tag ${{ env.APP_NAME }}:latest ${{ env.APP_NAME }}:${{ env.TAG_NAME }}
